### ISSUE TITLE
Change method

### ISSUE THREAD

**Issue by Mottie** [brejep/additive-transform-js#1]
Wouldn't it be easier to copy the transform value to the style? That way you can support all transforms, including 3D, without doing all the matrix calculations. Here is your original demo roughly modified: http://jsfiddle.net/Mottie/eGDP7/3/

``` js
function getCSSRulesForClass( selector ) {
    var sheets = document.styleSheets;
    var cssRules = [];
    for (var i = 0; i<sheets.length; ++i) {
        var sheet = sheets[i];
        if( !sheet.cssRules ) { continue; }
        for (var j = 0; j < sheet.cssRules.length; ++j ) {
            var rule = sheet.cssRules[j];
            if (rule.selectorText && rule.selectorText.split(',').indexOf(selector) !== -1) {
                var styles = rule.style;
                for( var k = 0; k<styles.length; ++k ) {
                    var style = styles[k];
                    cssRules.push( { 
                        property: style,
                        value: styles[style]
                    } );
                }
            }
        }
    }
    return cssRules;
}

var allTransformedNodes = document.querySelectorAll(".compoundtransform"),
    transformedNode,
    transformationSelectors,
    transformationSelector;

for( var i=0; i<allTransformedNodes.length; ++i ) {
    transformedNode = allTransformedNodes[i];
    transformationSelectors = transformedNode.getAttribute("data-transformations").split(/[\s+,]/);

    for( var j=0; j<transformationSelectors.length; ++j ) {
        transformationSelector = transformationSelectors[j];
        addTransform( transformedNode, "." + transformationSelector );
    }
}

function addTransform( transformedNode, transformationClass ) {                
    var transform,
        transformValue = '',
        transformationRules = getCSSRulesForClass( transformationClass );
    for( var i = 0; i<transformationRules.length; ++i ) {
        var rule = transformationRules[i];
        if ( /transform$/.test(rule.property) ) {
            transform = rule.property;
            transformValue += ' ' + rule.value;
        }
    }
    transformedNode.style[ transform ] += transformValue;
}
```

**Comment by BrettJephson** [comment]
I'd almost forgotten about this.

I like matrices because they make me feel clever but you are right - it is always better to let the system do the work for you!

I'll take a look at integrating your changes. Thanks.

**Comment by BrettJephson** [comment]
I think the two solutions do slightly different things: 
- Here is my test.html in jsfiddle - http://jsfiddle.net/sLzpws5e/
- And here is the same with your revised js - http://jsfiddle.net/4r7ydbps/

I think the difference is with the matrix I can add two scaling or translate classes on to one another. By setting a style I can handle the various components of a class but a scale will replace a previous scale value. 

I'm going to look at this again and see if I can make the whole thing a bit more modular.

Thanks for reminding me about it.

**Comment by Mottie** [comment]
Thanks for digging into this again! :shaved_ice: 

Maybe you could just use the matrix if you find duplicate transform types?
